[packages.siafi_2023]
path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2023/main/datapackage.json"
token = "GH_TOKEN"
resources = [
    "receita",
]

[packages.siafi_2024]
path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2024/main/datapackage.json"
token = "GH_TOKEN"
resources = [
    "receita",
]

[packages.siafi_2025]
path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2025/main/datapackage.json"
token = "GH_TOKEN"
resources = [
    "receita",
]

[packages.siafi_2026]
path = "https://raw.githubusercontent.com/splor-mg/dados-armazem-siafi-2026/main/datapackage.json"
token = "GH_TOKEN"
resources = [
    "receita",
]

[packages.reestimativa_2026]
path = "https://raw.githubusercontent.com/splor-mg/dados-reestimativa-2026/main/datapackage.json"
token = "GH_TOKEN"
resources = [
    "reest_rec",
]

[packages.dados-aux-classificadores]
path = "https://raw.githubusercontent.com/splor-mg/dados-aux-classificadores/main/datapackage.json"
token = "GH_TOKEN"
resources = [
    "uo",
    "fonte_recurso",
]
